# Generated by Django 4.1.2 on 2022-11-01 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=255)),
                ('address_json', models.JSONField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('FB', 'Flag-football'), ('HK', 'Hockey'), ('SB', 'Softball'), ('BK', 'Basketball')], default='FB', max_length=2)),
                ('status', models.CharField(choices=[('DRA', 'Draft'), ('CRE', 'Create'), ('SUB', 'Submitted')], default='DRA', max_length=3)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
