# Generated by Django 4.1.2 on 2022-11-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRA', 'Draft'), ('SUB', 'Submitted'), ('PST', 'Post'), ('REJ', 'Rejected'), ('ARC', 'Archived')], default='DRA', max_length=3),
        ),
    ]
