# Generated by Django 4.1.2 on 2022-11-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FB', 'Flag-football'), ('HK', 'Hockey'), ('SB', 'Softball'), ('BK', 'Basketball')], default='', max_length=2),
        ),
    ]
