# Generated by Django 4.1.3 on 2022-11-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Flag-football', 'Flag-football'), ('Hockey', 'Hockey'), ('Softball', 'Softball'), ('Basketball', 'Basketball')], default='Flag-football', max_length=13),
        ),
    ]
