# Generated by Django 4.1.3 on 2022-11-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_reserved_by_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('NWP', 'Northwest Park'), ('GPK', 'Gary L. Pittman Park'), ('PVC', 'Pavilion Recreation Complex'), ('GWP', 'Gower Park'), ('STF', 'Stevens Field'), ('LSP', 'Lakeside Park'), ('ABC', 'ABC Sports Center'), ('NSP', 'Northside Park')], default='NWP', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.CharField(choices=[('ACMY', 'ACMY of Greenville'), ('ABC', 'ABC Sports Center')], default='ACMY', max_length=4),
        ),
    ]
