# Generated by Django 4.1.3 on 2022-11-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_location_alter_post_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reserved_by_username',
        ),
    ]
