# Generated by Django 4.1.3 on 2022-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_reserved_by_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('Northwest Park', 'Northwest Park'), ('Gary L. Pittman Park', 'Gary L. Pittman Park'), ('Pavilion Recreation Complex', 'Pavilion Recreation Complex'), ('Gower Park', 'Gower Park'), ('Stevens Field', 'Stevens Field'), ('Lakeside Park', 'Lakeside Park'), ('ABC Sports Center', 'ABC Sports Center'), ('Northside Park', 'Northside Park')], default='Northwest Park', max_length=28),
        ),
    ]
