# Generated by Django 4.1.3 on 2022-11-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='organization',
            field=models.CharField(choices=[('ACMY of Greenville', 'ACMY of Greenville'), ('ABC Sports Center', 'ABC Sports Center')], default='ACMY of Greenville', max_length=18),
        ),
    ]
