# Generated by Django 4.1.3 on 2022-11-05 18:12

from django.db import migrations
import localflavor.us.models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
